"""Flag claim regressions for contextual review; this is not a truth detector."""
import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PATTERNS = [
    r"LLMs cannot", r"model cannot", r"general abduction",
    r"autonomous scientific discovery", r"representation invention",
    r"independent replication", r"\bproves\b", r"zero false-positive rate",
    r"model generated the successful theory", r"motif realizer is irreplaceable",
    r"first ever", r"solve[s]? abduction", r"unseen functional-form invention",
    r"In the rapidly evolving landscape", r"This underscores", r"It is important to note",
    r"\bcrucially\b", r"not merely", r"\bparadigm\b", r"groundbreaking", r"\bunlock\b", r"transformative",
]


def main():
    files = [ROOT / "manuscript/AIJ_MANUSCRIPT.md", ROOT / "manuscript/AIJ_SUPPLEMENTARY_METHODS.md"]
    report = [
        "# AIJ claim-regression inventory", "",
        "Generated by `scripts/audit_aij_claims.py`. This script locates contextual flags; it does not verify claims or certify prose quality.", "",
        "The manual review and disposition of the section-review findings are recorded in `reports/AIJ_SECTION_REVIEW_RESOLUTION.md`. Scientific checks are in `reports/AIJ_NUMERICAL_CHECKS.json` and `reports/AIJ_CONTRACT_AUDIT.json`.", "",
        "## Contextual flags", "",
        "| File:line | Pattern | Context |", "|---|---|---|",
    ]
    count = 0
    for file in files:
        for i, line in enumerate(file.read_text().splitlines(), 1):
            for pattern in PATTERNS:
                if re.search(pattern, line, re.I):
                    count += 1
                    context = line.replace("|", "/")
                    report.append(f"| {file.name}:{i} | `{pattern}` | {context} |")
    report += ["", f"Flagged occurrences: {count}. These include necessary limitations, literal protocol terms and reference titles; a match is not an error verdict.", "",
               "## Audited source hashes", ""]
    for file in files:
        report.append(f"- `{file.relative_to(ROOT)}`: `{hashlib.sha256(file.read_bytes()).hexdigest()}`")
    report += ["", "## Paragraph-level scope-language inventory", "",
               "Narrative paragraphs only, excluding headings, metadata, equations, tables, references, code and captions. Cue matching identifies paragraphs for contextual review; it does not decide whether a qualification is necessary or redundant.", "",
               "| Source:line | Paragraph opening | Cue match |", "|---|---|---|"]
    cues = re.compile(r"\bnot\b|\bno\b|\bcannot\b|\bonly\b|\brather than\b|\bconfound|\bbound(?:ed|ary|aries)\b|\bfixed\b|\bpost-hoc\b|\bsynthetic\b|\bsupplied\b|\bdescriptive\b|\bdistinct\b", re.I)
    for file in files:
        section = ""; in_code = False
        for i, line in enumerate(file.read_text().splitlines(), 1):
            if line.startswith("## "): section = line
            if line.startswith("```"): in_code = not in_code; continue
            if in_code or not line or line.startswith(("#", "|", "![", "Figure ", "Table ", "\\", "h_0", "a^*", "- ")): continue
            if file.name == "AIJ_MANUSCRIPT.md" and not re.match(r"## [1-8]\. ", section): continue
            if len(line.split()) < 15: continue
            label = "Scope-language cue" if cues.search(line) else "No configured cue"
            opening = " ".join(line.split()[:14]).replace("|", "/") + " ..."
            report.append(f"| {file.name}:{i} | {opening} | {label} |")
    (ROOT / "reports/AIJ_CLAIM_REGRESSION_AUDIT.md").write_text("\n".join(report) + "\n")
    print(f"Claim inventory: {count} contextual flags; manual dispositions are separate.")


if __name__ == "__main__":
    main()
